# Packages
library(tidyverse)
library(janitor)
library(lubridate)
library(readxl)
library(rvest)
library(stringi)
library(data.table)
library(quanteda)
library(quanteda.textstats)
library(quanteda.textmodels)
library(sf)
library(stm)